// EXPORTS: ACTIVITY_TYPES, IActivityDef, getActivityDef
export type ActivityMode = 'click-collect' | 'drag-match' | 'click-make';

export interface IActivityDef {
  mode: ActivityMode;
  title: string;
  description: string;
  /** 点击收集类：目标物数量 */
  targetCount?: number;
  /** 点击收集类：目标物 emoji 列表 */
  targets?: string[];
  /** 拖拽匹配类：左侧食材（键名）与右侧槽位（值名）的映射 */
  pairs?: Record<string, string>;
  /** 点击制作类：步骤列表 */
  steps?: string[];
  reward: number;
  icon: string;
}

/** 按活动名称（中文）匹配的活动交互定义 */
const ACTIVITY_LIBRARY: Record<string, IActivityDef> = {
  '咬春饼': {
    mode: 'drag-match',
    title: '咬春饼',
    description: '将食材拖入春饼中，卷出新春滋味',
    pairs: { '韭菜': '饼皮', '豆芽': '饼皮', '萝卜丝': '饼皮', '肉丝': '饼皮' },
    reward: 10,
    icon: '🫓',
  },
  '贴春胜': {
    mode: 'click-make',
    title: '贴春胜',
    description: '依步骤剪彩为胜，迎立新春',
    steps: ['取彩纸', '折方形', '剪花纹', '展春胜'],
    reward: 10,
    icon: '✂️',
  },
  '踏青寻花': {
    mode: 'click-collect',
    title: '踏青寻花',
    description: '点击找出藏在草丛中的野花',
    targetCount: 6,
    targets: ['🌸', '🌼', '🌺', '🌷', '💐', '🌹'],
    reward: 10,
    icon: '🌷',
  },
  '接雨水煮茶': {
    mode: 'click-collect',
    title: '接雨水煮茶',
    description: '点击雨滴收集春雨水',
    targetCount: 8,
    targets: ['💧', '💧', '💧', '💧', '🍵', '🍃', '💧', '💧'],
    reward: 10,
    icon: '🍵',
  },
  '挂风铃': {
    mode: 'click-make',
    title: '挂风铃',
    description: '依序悬挂风铃，听风动之声',
    steps: ['取铜铃', '系红绳', '挂檐下', '听风声'],
    reward: 10,
    icon: '🔔',
  },
  '赏雨': {
    mode: 'click-collect',
    title: '赏雨',
    description: '点击雨滴，静赏春雨',
    targetCount: 10,
    targets: ['💧', '💧', '🌧️', '💧', '💧', '☔', '💧', '💧', '🌧️', '💧'],
    reward: 8,
    icon: '☔',
  },
  '蒙鼓皮': {
    mode: 'click-make',
    title: '蒙鼓皮',
    description: '春雷乍响，依序蒙制新鼓',
    steps: ['选木料', '绷紧皮', '钉鼓钉', '试鼓声'],
    reward: 10,
    icon: '🥁',
  },
  '听雷寻虫': {
    mode: 'click-collect',
    title: '听雷寻虫',
    description: '点击找出被春雷惊醒的小虫',
    targetCount: 6,
    targets: ['🐛', '🐞', '🦗', '🐛', '🐝', '🦋'],
    reward: 10,
    icon: '🐛',
  },
  '种桃花': {
    mode: 'click-make',
    title: '种桃花',
    description: '依步骤种下一棵桃树',
    steps: ['掘土坑', '栽树苗', '培新土', '浇春水'],
    reward: 10,
    icon: '🌸',
  },
  '立蛋': {
    mode: 'click-make',
    title: '立蛋',
    description: '春分竖蛋，步步小心',
    steps: ['取鲜蛋', '找平面', '耐心放', '稳竖立'],
    reward: 10,
    icon: '🥚',
  },
  '放纸鸢': {
    mode: 'drag-match',
    title: '放纸鸢',
    description: '将纸鸢与正确的线轴配对',
    pairs: { '燕子鸢': '红线轴', '蝴蝶鸢': '绿线轴', '沙燕鸢': '蓝线轴', '金鱼鸢': '金线轴' },
    reward: 10,
    icon: '🪁',
  },
  '采春菜': {
    mode: 'click-collect',
    title: '采春菜',
    description: '点击采摘田野里的春菜',
    targetCount: 7,
    targets: ['🥬', '🥬', '🌱', '🥬', '🌿', '🥬', '🥬'],
    reward: 10,
    icon: '🥬',
  },
  '插柳': {
    mode: 'click-make',
    title: '插柳',
    description: '清明插柳，依序完成',
    steps: ['折新柳', '入清水', '插门前', '寄相思'],
    reward: 10,
    icon: '🌿',
  },
  '做青团': {
    mode: 'drag-match',
    title: '做青团',
    description: '将馅料拖入青团皮中',
    pairs: { '豆沙馅': '青团皮', '芝麻馅': '青团皮', '蛋黄馅': '青团皮', '荠菜馅': '青团皮' },
    reward: 10,
    icon: '🍡',
  },
  '踏青写生': {
    mode: 'click-collect',
    title: '踏青写生',
    description: '点击收集春日美景入画',
    targetCount: 6,
    targets: ['🌸', '🦋', '🌿', '☀️', '🏞️', '🐦'],
    reward: 10,
    icon: '🎨',
  },
  '采新茶': {
    mode: 'click-collect',
    title: '采新茶',
    description: '点击采摘茶树上的嫩芽',
    targetCount: 8,
    targets: ['🍃', '🍃', '🌿', '🍃', '🍃', '🌱', '🍃', '🍃'],
    reward: 10,
    icon: '🍵',
  },
  '赏牡丹': {
    mode: 'click-collect',
    title: '赏牡丹',
    description: '点击找出所有盛开的牡丹',
    targetCount: 5,
    targets: ['🌺', '🌸', '🌺', '🌷', '🌺'],
    reward: 8,
    icon: '🌺',
  },
  '喂鱼': {
    mode: 'click-collect',
    title: '喂鱼',
    description: '点击投喂池塘中的游鱼',
    targetCount: 7,
    targets: ['🐟', '🐠', '🐡', '🐟', '🐠', '🐟', '🐡'],
    reward: 8,
    icon: '🐟',
  },
  '称人': {
    mode: 'click-make',
    title: '称人',
    description: '立夏称体重，依序完成',
    steps: ['挂杆秤', '坐竹椅', '移秤砣', '报斤两'],
    reward: 10,
    icon: '⚖️',
  },
  '斗蛋': {
    mode: 'drag-match',
    title: '斗蛋',
    description: '将彩蛋两两配对相斗',
    pairs: { '红彩蛋': '蓝彩蛋', '黄彩蛋': '绿彩蛋', '紫彩蛋': '橙彩蛋', '粉彩蛋': '青彩蛋' },
    reward: 10,
    icon: '🥚',
  },
  '尝新': {
    mode: 'click-collect',
    title: '尝新',
    description: '点击品尝初夏新果',
    targetCount: 6,
    targets: ['🍒', '🍓', '🥒', '🍑', '🥝', '🍈'],
    reward: 10,
    icon: '🍒',
  },
  '动三车': {
    mode: 'click-make',
    title: '动三车',
    description: '依序启动水车、油车、丝车',
    steps: ['踏水车', '转油车', '摇丝车', '庆丰收'],
    reward: 10,
    icon: '⚙️',
  },
  '缫丝小体验': {
    mode: 'click-make',
    title: '缫丝小体验',
    description: '依步骤体验抽茧成丝',
    steps: ['选蚕茧', '入沸水', '寻丝头', '抽丝线'],
    reward: 10,
    icon: '🧵',
  },
  '看麦黄': {
    mode: 'click-collect',
    title: '看麦黄',
    description: '点击找出金黄色的麦穗',
    targetCount: 7,
    targets: ['🌾', '🌾', '🌱', '🌾', '🌾', '🌿', '🌾'],
    reward: 8,
    icon: '🌾',
  },
  '插秧': {
    mode: 'click-make',
    title: '插秧',
    description: '依步骤插下一株株新稻',
    steps: ['整水田', '取秧苗', '插秧行', '望丰收'],
    reward: 10,
    icon: '🌾',
  },
  '送花神': {
    mode: 'click-collect',
    title: '送花神',
    description: '点击收集落花送花神',
    targetCount: 8,
    targets: ['🌸', '🌺', '🌷', '🌹', '💐', '🌼', '🌸', '🌺'],
    reward: 10,
    icon: '🌸',
  },
  '煮梅': {
    mode: 'click-make',
    title: '煮梅',
    description: '依步骤煮一锅青梅酒',
    steps: ['选青梅', '入瓷坛', '加冰糖', '封坛藏'],
    reward: 10,
    icon: '🍶',
  },
  '夏至面': {
    mode: 'drag-match',
    title: '夏至面',
    description: '将配料拖入面碗中',
    pairs: { '细面条': '青瓷碗', '黄瓜丝': '青瓷碗', '麻酱汁': '青瓷碗', '鸡蛋丝': '青瓷碗' },
    reward: 10,
    icon: '🍜',
  },
  '祭神祀祖': {
    mode: 'click-make',
    title: '祭神祀祖',
    description: '依序完成夏至祭祀',
    steps: ['备祭品', '点香烛', '行祭礼', '祈安康'],
    reward: 10,
    icon: '🕯️',
  },
  '观星': {
    mode: 'click-collect',
    title: '观星',
    description: '点击找出夜空中的亮星',
    targetCount: 8,
    targets: ['⭐', '✨', '🌟', '⭐', '✨', '🌟', '⭐', '✨'],
    reward: 10,
    icon: '⭐',
  },
  '晒书晒衣': {
    mode: 'click-make',
    title: '晒书晒衣',
    description: '依序晒出书画与衣裳',
    steps: ['搬书箱', '晾书画', '晒衣裳', '除潮气'],
    reward: 10,
    icon: '📚',
  },
  '食藕': {
    mode: 'drag-match',
    title: '食藕',
    description: '将藕片与调料配对',
    pairs: { '白藕片': '冰糖汁', '藕夹肉': '糯米馅', '糖醋藕': '糖醋汁', '藕粉羹': '桂花糖' },
    reward: 10,
    icon: '🪷',
  },
  '捕萤': {
    mode: 'click-collect',
    title: '捕萤',
    description: '点击捕捉飞舞的萤火虫',
    targetCount: 7,
    targets: ['✨', '💫', '✨', '🌟', '✨', '💫', '✨'],
    reward: 10,
    icon: '✨',
  },
  '伏茶摊': {
    mode: 'click-make',
    title: '伏茶摊',
    description: '依步骤煮一锅消暑伏茶',
    steps: ['选茶叶', '入大缸', '加冰糖', '施路人'],
    reward: 10,
    icon: '🍵',
  },
  '赏荷': {
    mode: 'click-collect',
    title: '赏荷',
    description: '点击找出所有盛开的荷花',
    targetCount: 6,
    targets: ['🪷', '🌸', '🪷', '🌺', '🪷', '🪷'],
    reward: 8,
    icon: '🪷',
  },
  '冰碗消暑': {
    mode: 'drag-match',
    title: '冰碗消暑',
    description: '将鲜果拖入冰碗中',
    pairs: { '西瓜片': '冰碗', '荔枝': '冰碗', '葡萄': '冰碗', '桃子': '冰碗' },
    reward: 10,
    icon: '🧊',
  },
  '啃秋': {
    mode: 'click-make',
    title: '啃秋',
    description: '立秋啃瓜，依步骤品秋味',
    steps: ['选西瓜', '切两半', '舀瓜瓤', '咬秋意'],
    reward: 10,
    icon: '🍉',
  },
  '贴秋膘': {
    mode: 'drag-match',
    title: '贴秋膘',
    description: '将佳肴与餐盘配对',
    pairs: { '红烧肉': '青瓷盘', '清蒸鱼': '白瓷盘', '炖排骨': '陶碗', '卤鸭': '木盘' },
    reward: 10,
    icon: '🍖',
  },
  '晒秋': {
    mode: 'click-collect',
    title: '晒秋',
    description: '点击收集晒架上的秋实',
    targetCount: 7,
    targets: ['🌶️', '🌽', '🍆', '🥕', '🧄', '🍠', '🫑'],
    reward: 10,
    icon: '🌽',
  },
  '放河灯': {
    mode: 'click-make',
    title: '放河灯',
    description: '依序制作并放流河灯',
    steps: ['折纸荷', '点烛火', '入秋水', '寄思念'],
    reward: 10,
    icon: '🪷',
  },
  '开渔': {
    mode: 'click-collect',
    title: '开渔',
    description: '点击收获开渔后的鲜鱼',
    targetCount: 6,
    targets: ['🐟', '🦐', '🦀', '🐠', '🦑', '🐡'],
    reward: 10,
    icon: '🎣',
  },
  '采菱': {
    mode: 'click-collect',
    title: '采菱',
    description: '点击采摘水面上的菱角',
    targetCount: 7,
    targets: ['🔺', '🔻', '🔺', '🍂', '🔺', '🔻', '🔺'],
    reward: 8,
    icon: '🌰',
  },
  '收清露': {
    mode: 'click-collect',
    title: '收清露',
    description: '点击收集花叶上的白露',
    targetCount: 8,
    targets: ['💧', '💧', '🍃', '💧', '💧', '🌸', '💧', '💧'],
    reward: 10,
    icon: '💧',
  },
  '酿米酒': {
    mode: 'click-make',
    title: '酿米酒',
    description: '依步骤酿造白露米酒',
    steps: ['选新米', '蒸米饭', '加酒曲', '入坛封'],
    reward: 10,
    icon: '🍶',
  },
  '打枣': {
    mode: 'click-collect',
    title: '打枣',
    description: '点击打落树上的红枣',
    targetCount: 7,
    targets: ['🔴', '🟤', '🔴', '🟤', '🔴', '🔴', '🟤'],
    reward: 10,
    icon: '🌰',
  },
  '竖蛋': {
    mode: 'click-make',
    title: '竖蛋',
    description: '秋分竖蛋，步步小心',
    steps: ['选鲜蛋', '找平面', '耐心放', '稳竖立'],
    reward: 10,
    icon: '🥚',
  },
  '送秋牛图': {
    mode: 'click-make',
    title: '送秋牛图',
    description: '依序制作秋牛图',
    steps: ['取红纸', '拓印版', '题吉语', '送乡邻'],
    reward: 10,
    icon: '🖼️',
  },
  '赏月': {
    mode: 'click-collect',
    title: '赏月',
    description: '点击找出秋夜明月美景',
    targetCount: 6,
    targets: ['🌕', '⭐', '🌕', '✨', '🌙', '🌕'],
    reward: 10,
    icon: '🌕',
  },
  '赏菊': {
    mode: 'click-collect',
    title: '赏菊',
    description: '点击找出所有盛开的菊花',
    targetCount: 7,
    targets: ['🌼', '🌸', '🌼', '🌻', '🌼', '🌼', '🌺'],
    reward: 10,
    icon: '🌼',
  },
  '登高': {
    mode: 'click-make',
    title: '登高',
    description: '依步骤攀登秋日山巅',
    steps: ['备行囊', '踏石径', '穿枫林', '登绝顶'],
    reward: 10,
    icon: '⛰️',
  },
  '钓秋蟹': {
    mode: 'click-collect',
    title: '钓秋蟹',
    description: '点击钓出肥美的秋蟹',
    targetCount: 5,
    targets: ['🦀', '🐟', '🦀', '🦐', '🦀'],
    reward: 10,
    icon: '🦀',
  },
  '赏红叶': {
    mode: 'click-collect',
    title: '赏红叶',
    description: '点击收集最美的红叶',
    targetCount: 7,
    targets: ['🍁', '🍂', '🍁', '🍁', '🍂', '🍁', '🍂'],
    reward: 8,
    icon: '🍁',
  },
  '吃柿子': {
    mode: 'click-make',
    title: '吃柿子',
    description: '依步骤品尝霜降甜柿',
    steps: ['摘红柿', '去柿蒂', '剥柿皮', '品柿甜'],
    reward: 10,
    icon: '🍅',
  },
  '进补': {
    mode: 'drag-match',
    title: '进补',
    description: '将补品与碗盏配对',
    pairs: { '银耳羹': '白瓷碗', '红枣汤': '陶砂煲', '百合粥': '青瓷碗', '栗子羹': '木碗' },
    reward: 10,
    icon: '🍲',
  },
  '包饺子': {
    mode: 'drag-match',
    title: '包饺子',
    description: '将馅料拖入饺子皮中',
    pairs: { '白菜馅': '饺子皮', '韭菜馅': '饺子皮', '三鲜馅': '饺子皮', '芹菜馅': '饺子皮' },
    reward: 10,
    icon: '🥟',
  },
  '酿酒': {
    mode: 'click-make',
    title: '酿酒',
    description: '依步骤酿造冬酒',
    steps: ['选糯米', '蒸酒饭', '加酒药', '窖中藏'],
    reward: 10,
    icon: '🍶',
  },
  '备冬衣': {
    mode: 'click-make',
    title: '备冬衣',
    description: '依序整理冬日衣裳',
    steps: ['取棉袍', '缝新扣', '叠齐整', '入樟箱'],
    reward: 10,
    icon: '🧥',
  },
  '腌菜': {
    mode: 'click-make',
    title: '腌菜',
    description: '依步骤腌制冬日咸菜',
    steps: ['选鲜菜', '晒半干', '入坛腌', '待发酵'],
    reward: 10,
    icon: '🥬',
  },
  '打糍粑': {
    mode: 'click-make',
    title: '打糍粑',
    description: '依步骤捣制软糯糍粑',
    steps: ['蒸糯饭', '入石臼', '捣成团', '滚豆粉'],
    reward: 10,
    icon: '🍡',
  },
  '围炉煮茶': {
    mode: 'click-make',
    title: '围炉煮茶',
    description: '依序围炉煮茶取暖',
    steps: ['生炭火', '架铜壶', '投茶叶', '品茶香'],
    reward: 10,
    icon: '🫖',
  },
  '踏雪寻梅': {
    mode: 'click-collect',
    title: '踏雪寻梅',
    description: '点击找出雪中的红梅',
    targetCount: 6,
    targets: ['🌸', '❄️', '🌸', '❄️', '❄️', '🌸'],
    reward: 10,
    icon: '🌸',
  },
  '堆雪人': {
    mode: 'click-make',
    title: '堆雪人',
    description: '依步骤堆一个小雪人',
    steps: ['滚雪团', '叠身形', '按五官', '戴红帽'],
    reward: 10,
    icon: '⛄',
  },
  '温酒': {
    mode: 'click-make',
    title: '温酒',
    description: '依步骤烫一壶暖酒',
    steps: ['取酒壶', '入热水', '等酒香', '入杯饮'],
    reward: 10,
    icon: '🍶',
  },
  '包饺子汤圆': {
    mode: 'drag-match',
    title: '包饺子汤圆',
    description: '南北冬至美食一起做',
    pairs: { '肉馅': '饺子皮', '豆沙馅': '汤圆皮', '菜馅': '饺子皮', '芝麻馅': '汤圆皮' },
    reward: 10,
    icon: '🥟',
  },
  '九九消寒图': {
    mode: 'click-make',
    title: '九九消寒图',
    description: '依步骤点染消寒图',
    steps: ['铺素纸', '画梅枝', '点花瓣', '待春归'],
    reward: 10,
    icon: '🌸',
  },
  '祭祖': {
    mode: 'click-make',
    title: '祭祖',
    description: '依序完成冬至祭祖',
    steps: ['设供桌', '点香烛', '行跪拜', '寄追思'],
    reward: 10,
    icon: '🕯️',
  },
  '探梅': {
    mode: 'click-collect',
    title: '探梅',
    description: '点击找出初绽的腊梅',
    targetCount: 6,
    targets: ['🌼', '❄️', '🌼', '🌼', '❄️', '🌼'],
    reward: 10,
    icon: '🌼',
  },
  '冰戏': {
    mode: 'click-collect',
    title: '冰戏',
    description: '点击收集冰上嬉戏之物',
    targetCount: 6,
    targets: ['⛸️', '❄️', '🛷', '🧊', '❄️', '⛸️'],
    reward: 10,
    icon: '⛸️',
  },
  '画梅花': {
    mode: 'click-make',
    title: '画梅花',
    description: '依步骤画一枝寒梅',
    steps: ['铺宣纸', '写老干', '点新花', '题诗句'],
    reward: 10,
    icon: '🖌️',
  },
  '办年货': {
    mode: 'drag-match',
    title: '办年货',
    description: '将年货与提篮配对',
    pairs: { '红纸联': '竹篮', '花生糖': '瓷罐', '新衣料': '布包', '香烛台': '木盒' },
    reward: 10,
    icon: '🧧',
  },
  '扫尘': {
    mode: 'click-make',
    title: '扫尘',
    description: '依序扫除房屋尘垢',
    steps: ['取扫帚', '扫屋顶', '擦门窗', '净庭院'],
    reward: 10,
    icon: '🧹',
  },
  '尾牙祭': {
    mode: 'click-make',
    title: '尾牙祭',
    description: '依序完成岁末尾牙祭',
    steps: ['备三牲', '点红烛', '敬土地', '宴乡邻'],
    reward: 10,
    icon: '🏮',
  },
};

export function getActivityDef(name: string): IActivityDef {
  if (ACTIVITY_LIBRARY[name]) return ACTIVITY_LIBRARY[name];
  // 兜底：点击收集
  return {
    mode: 'click-collect',
    title: name,
    description: '点击收集节日风物',
    targetCount: 6,
    targets: ['✨', '🌟', '💫', '⭐', '✨', '🌟'],
    reward: 10,
    icon: '✨',
  };
}
